repos:
  - repo: https://github.com/stephendavid77/opal-dev-tools
    rev: 49317b2 # Specific commit hash
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: black
      - id: isort
      - id: flake8
      - id: mypy
      - id: bandit
      - id: eslint
      - id: prettier
      - id: check-dependencies
      - id: check-imports
      - id: check-structure
      - id: pytest